nameOverride: ""
fullnameOverride: ""

image:
  # Vigilo is not currently available on Docker Hub
  # You will need to build and push your own image to a registry
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is latest
  tag: ""

imagePullSecrets:
  - name: ""

configs:
  urls:
    configMapName: ""
    # Represents the content of the urls.json file
    pages:
      Test: ["https://www.wikipedia.org"]

  lighthouse:
    configMapName: ""
    # Represents the content of the lh-config.js file
    lighthouseConfig: |
      export default {
        extends: 'lighthouse:default',
        settings: {
            onlyAudits: [
                "largest-contentful-paint",
                "first-contentful-paint",
                "cumulative-layout-shift",
                "total-blocking-time",
                "speed-index",
                "total-byte-weight",
                "server-response-time",
                "is-crawlable",
                "screenshot-thumbnails"
            ]
        }
      }
