apiVersion: batch/v1
kind: CronJob
metadata:
  name: vigilo-cron
spec:
  schedule: "*/10 * * * *" # every minute
  concurrencyPolicy: Forbid # skip if previous job is still running
  successfulJobsHistoryLimit: 0 # keep no history of successful jobs
  failedJobsHistoryLimit: 1 # keep only one failed job
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: urls-volume
              configMap:
                name: vigilo-urls
            - name: lh-config-volume
              configMap:
                name: vigilo-lh-config
          containers:
          - name: vigilo
            image: registry.seraphinus.dev/vigilo:latest
            imagePullPolicy: Always
            volumeMounts:
              - name: urls-volume
                mountPath: ./app/urls.json
                subPath: urls.json
              - name: lh-config-volume
                mountPath: ./app/lh-config.js
                subPath: lh-config.js
            envFrom:
              - secretRef:
                  {{- if .Values.existingDatadogSecret }}
                    name: {{ .Values.existingDatadogSecret }}
                  {{- else }}
                    name: vigilo-datadog-secret
                  {{- end }}
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure