{{- if not .Values.existingDatadogSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.datadogSecret.secretName | default "vigilo-datadog-secret" }}
  labels:
    {{- include "vigilo.labels" . | nindent 4 }}
data:
  DD_API_KEY: {{ .Values.datadogSecret.apiKey | required "datadogSecret.apiKey is required!" }}
  DD_APP_KEY: {{ .Values.datadogSecret.appKey | required "datadogSecret.appKey is required!" }}
{{- end}}