{{- if .Values.configs.datadogSecret.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vigilo.datadogSecret.name" . }}
data:
{{- with .Values.configs.datadogSecret.keys.apiKey }}
    DD_API_KEY: {{ . | b64enc | quote }}
{{- end }}
{{- with .Values.configs.datadogSecret.keys.appKey }}
    DD_APP_KEY: {{ . | b64enc | quote }}
{{- end }}
{{- end }}