apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *" # every minute
  concurrencyPolicy: Forbid # skip if previous job is still running
  successfulJobsHistoryLimit: 0 # keep no history of successful jobs
  failedJobsHistoryLimit: 1 # keep only one failed job
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure