urls:
  Test: ["https://www.wikipedia.org"]

lhConfig: |
  export default {
      extends: 'lighthouse:default',
      settings: {
          onlyAudits: [
              "largest-contentful-paint",
              "first-contentful-paint",
              "cumulative-layout-shift",
              "total-blocking-time",
              "speed-index",
              "total-byte-weight",
              "server-response-time",
              "is-crawlable",
              "screenshot-thumbnails"
          ]
      }
  }

existingDatadogSecret: ""

# Pass base64 encoded values for apiKey and appKey
# echo -n "<KEY>" | base64
datadogSecret:
  secretName:
  apiKey:
  appKey:
